package view;

import java.awt.Frame;
import javax.swing.JButton;
import model.Graph;
import model.Vertex;

/**
 * Main Menu where the user can interact with the whole app and graph
 *
 * @author Arístides Pérez
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu to set the board with vertices data
     *
     * @param soupGraph graph to create board
     */
    public Menu(Graph<Character> soupGraph) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        JButton[] boardArray = {aBoard, bBoard, cBoard, dBoard, eBoard,
            fBoard, gBoard, hBoard, iBoard, jBoard, kBoard, lBoard, mBoard,
            nBoard, oBoard, pBoard};

        Vertex[] vertices = soupGraph.getVertices();
        
        for (int i = 0; i < soupGraph.getMaxVertices(); i++) {

            boardArray[i].setText(vertices[i].getData().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        board = new javax.swing.JPanel();
        aBoard = new javax.swing.JButton();
        bBoard = new javax.swing.JButton();
        cBoard = new javax.swing.JButton();
        dBoard = new javax.swing.JButton();
        eBoard = new javax.swing.JButton();
        fBoard = new javax.swing.JButton();
        gBoard = new javax.swing.JButton();
        hBoard = new javax.swing.JButton();
        iBoard = new javax.swing.JButton();
        jBoard = new javax.swing.JButton();
        kBoard = new javax.swing.JButton();
        lBoard = new javax.swing.JButton();
        mBoard = new javax.swing.JButton();
        nBoard = new javax.swing.JButton();
        oBoard = new javax.swing.JButton();
        pBoard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(255, 255, 255));

        exitButton.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        exitButton.setForeground(new java.awt.Color(51, 51, 51));
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("X");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        minimizeButton.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(51, 51, 51));
        minimizeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeButton.setText("-");
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Main.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 40));

        board.setBackground(new java.awt.Color(255, 255, 255));

        aBoard.setBackground(new java.awt.Color(51, 51, 51));
        aBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        aBoard.setForeground(new java.awt.Color(255, 255, 255));
        aBoard.setText("A");
        aBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        aBoard.setFocusPainted(false);
        aBoard.setFocusable(false);

        bBoard.setBackground(new java.awt.Color(51, 51, 51));
        bBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        bBoard.setForeground(new java.awt.Color(255, 255, 255));
        bBoard.setText("B");
        bBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bBoard.setFocusable(false);

        cBoard.setBackground(new java.awt.Color(51, 51, 51));
        cBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        cBoard.setForeground(new java.awt.Color(255, 255, 255));
        cBoard.setText("C");
        cBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cBoard.setFocusable(false);

        dBoard.setBackground(new java.awt.Color(51, 51, 51));
        dBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        dBoard.setForeground(new java.awt.Color(255, 255, 255));
        dBoard.setText("D");
        dBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        dBoard.setFocusable(false);

        eBoard.setBackground(new java.awt.Color(51, 51, 51));
        eBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        eBoard.setForeground(new java.awt.Color(255, 255, 255));
        eBoard.setText("E");
        eBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        eBoard.setFocusable(false);

        fBoard.setBackground(new java.awt.Color(51, 51, 51));
        fBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        fBoard.setForeground(new java.awt.Color(255, 255, 255));
        fBoard.setText("F");
        fBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        fBoard.setFocusable(false);

        gBoard.setBackground(new java.awt.Color(51, 51, 51));
        gBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        gBoard.setForeground(new java.awt.Color(255, 255, 255));
        gBoard.setText("G");
        gBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        gBoard.setFocusable(false);

        hBoard.setBackground(new java.awt.Color(51, 51, 51));
        hBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        hBoard.setForeground(new java.awt.Color(255, 255, 255));
        hBoard.setText("H");
        hBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hBoard.setFocusable(false);

        iBoard.setBackground(new java.awt.Color(51, 51, 51));
        iBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        iBoard.setForeground(new java.awt.Color(255, 255, 255));
        iBoard.setText("I");
        iBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        iBoard.setFocusable(false);

        jBoard.setBackground(new java.awt.Color(51, 51, 51));
        jBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        jBoard.setForeground(new java.awt.Color(255, 255, 255));
        jBoard.setText("J");
        jBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jBoard.setFocusable(false);

        kBoard.setBackground(new java.awt.Color(51, 51, 51));
        kBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        kBoard.setForeground(new java.awt.Color(255, 255, 255));
        kBoard.setText("K");
        kBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        kBoard.setFocusable(false);

        lBoard.setBackground(new java.awt.Color(51, 51, 51));
        lBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        lBoard.setForeground(new java.awt.Color(255, 255, 255));
        lBoard.setText("L");
        lBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lBoard.setFocusable(false);

        mBoard.setBackground(new java.awt.Color(51, 51, 51));
        mBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        mBoard.setForeground(new java.awt.Color(255, 255, 255));
        mBoard.setText("M");
        mBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mBoard.setFocusable(false);

        nBoard.setBackground(new java.awt.Color(51, 51, 51));
        nBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        nBoard.setForeground(new java.awt.Color(255, 255, 255));
        nBoard.setText("N");
        nBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nBoard.setFocusable(false);

        oBoard.setBackground(new java.awt.Color(51, 51, 51));
        oBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        oBoard.setForeground(new java.awt.Color(255, 255, 255));
        oBoard.setText("O");
        oBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        oBoard.setFocusable(false);

        pBoard.setBackground(new java.awt.Color(51, 51, 51));
        pBoard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        pBoard.setForeground(new java.awt.Color(255, 255, 255));
        pBoard.setText("P");
        pBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pBoard.setFocusable(false);

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(boardLayout.createSequentialGroup()
                            .addComponent(aBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(bBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(cBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(dBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(boardLayout.createSequentialGroup()
                            .addComponent(eBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(fBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(gBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(hBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(boardLayout.createSequentialGroup()
                            .addComponent(iBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(kBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(lBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(boardLayout.createSequentialGroup()
                            .addComponent(mBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(nBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(oBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(pBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Main.add(board, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JButton aBoard;
    private javax.swing.JButton bBoard;
    private javax.swing.JPanel board;
    private javax.swing.JButton cBoard;
    private javax.swing.JButton dBoard;
    private javax.swing.JButton eBoard;
    private javax.swing.JLabel exitButton;
    private javax.swing.JButton fBoard;
    private javax.swing.JButton gBoard;
    private javax.swing.JButton hBoard;
    private javax.swing.JButton iBoard;
    private javax.swing.JButton jBoard;
    private javax.swing.JButton kBoard;
    private javax.swing.JButton lBoard;
    private javax.swing.JButton mBoard;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JButton nBoard;
    private javax.swing.JButton oBoard;
    private javax.swing.JButton pBoard;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables

}
